avia_scanner/urls.py
from django.contrib import admin
from django.urls import path, include

from app.views import ticket_page_view, cities_lookup


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/city_ajax', cities_lookup),
    path('', ticket_page_view, name='tickets'),
]

from django.conf import settings
from django.urls import include

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

app/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'

app/forms.py
from django import forms

from .widgets import AjaxInputWidget
from .models import City

city_api = "/api/city_ajax"
attrs = {'class': 'inline right-margin'}


class SearchTicket(forms.Form):
    to_city = forms.CharField(widget=AjaxInputWidget(city_api, attrs=attrs))
    from_city = forms.CharField(widget=AjaxInputWidget(city_api, attrs=attrs))
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

app/views.py
import time
import random

from django.shortcuts import render
from django.http import JsonResponse
from django.core.cache import cache

from .models import City
from .forms import SearchTicket


def ticket_page_view(request):
    template = 'app/ticket_page.html'

    context = {
        'form': SearchTicket()
    }

    return render(request, template, context)


def cities_lookup(request):
    """Ajax request предлагающий города для автоподстановки, возвращает JSON"""
    results = cache.get("cities")
    if results is None:
        # TODO: Возможно это не самый оптимальный способ, но другого я не нашел.
        results = [i[0] for i in City.objects.all().values_list("name")]
        cache.set("cities", results, 20)
        print('---No cache')
    else:
        print('---From cache')
        # TODO: Почему debug_toolbar не показывает этот кэш?

    return JsonResponse(results, safe=False)

app/templates/widget/ajax_input_widget.html
<input type="text" id="id_{{ widget.name }}" name="{{ widget.name }}" {% include "django/forms/widgets/attrs.html" %} />
<script>
    $("#id_{{ widget.name }}").autocomplete({
        source: "{{ widget.url }}",
        selectFirst: true,
        minLength: 2,

    });
</script>

templates/app/ticket_page.html
<!doctype html>
<html lang="ru">
<head>
    <title>Магазин авиабилетов</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/avia.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

    <script type="text/javascript" src="{% static 'js/jquery3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

</head>
<body>

    <div class="container-fluid schampane">
        <div class="container">
            <div class="header padding-top">
                    <div >{{ form}}</div>
            </div>
        </div>
    </div>

<script>
  $(function () {
    $("#id_date").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
</script>

</body>

</html>